id: PB36417B6
initial_creation_type: input
source_metadata:
  title: Buddhagupta
  language: bo
  description: Instructions
  volume:
    8a7c83f1aba847adb7c3b56998accd79:
      title: An Extensive Commentary on the Four Immeasurables
      parent: Instructions
created_at: '2022-03-01T02:13:36.520308'
last_modified_at: '2022-03-01T02:13:36.520310'
statistics:
  total_words: 1888
  total_non_words: 191
quality:
  non_words_ratio: 0.1
